name: Deploy Bangla Archive Site
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout root and submodule
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100' # SDK Version to use
    - run: dotnet run -- deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}